import type {
  RecipeCategory,
  RecipeDifficulty,
  TechniqueIcon,
} from "../modules/recipes/recipe.model.js";

export const categories = [
  { slug: "mon-xao", name: "Món xào", displayOrder: 1 },
  { slug: "mon-canh", name: "Món canh", displayOrder: 2 },
  { slug: "mon-chien", name: "Món chiên", displayOrder: 3 },
  { slug: "mon-hap", name: "Món hấp", displayOrder: 4 },
  { slug: "mon-chay", name: "Món chay", displayOrder: 5 },
  { slug: "trang-mieng", name: "Tráng miệng", displayOrder: 6 },
] as const satisfies ReadonlyArray<{
  slug: string;
  name: RecipeCategory;
  displayOrder: number;
}>;

export const cookingTerms = {
  "phi thơm": "Cho dầu nóng rồi đảo hành hoặc tỏi đến khi dậy mùi thơm.",
  "áp chảo": "Làm chín nhanh thực phẩm trên chảo nóng với rất ít dầu.",
  "om nhỏ lửa": "Nấu liu riu ở nhiệt thấp để nguyên liệu mềm và thấm vị.",
  "trộn đều": "Đảo nhẹ các nguyên liệu để gia vị phủ đồng đều.",
  "hấp cách thủy":
    "Làm chín bằng hơi nước, không để thực phẩm chạm trực tiếp vào nước.",
} as const;

interface RecipeSeed {
  slug: string;
  title: string;
  image: string;
  imageAlt: string;
  difficulty: RecipeDifficulty;
  cookTimeMinutes: number;
  baseServings: number;
  category: RecipeCategory;
  mainIngredient: string;
  baseAmount: number;
  unit: string;
  prepNote: string;
  techniqueIcon: TechniqueIcon;
  ingredients: RecipeIngredientSeed[];
}

interface RecipeIngredientSeed {
  name: string;
  amount: number;
  unit: string;
  prepNote: string;
}

export const recipes: RecipeSeed[] = [
  {
    slug: "thit-bo-xao-bong-cai",
    title: "Thịt Bò Xào Bông Cải",
    image: "/images/recipes/thit-bo-xao-bong-cai.png",
    imageAlt: "Thịt bò xào với bông cải xanh",
    difficulty: "de",
    cookTimeMinutes: 20,
    baseServings: 2,
    category: "Món xào",
    mainIngredient: "Thịt bò và bông cải",
    baseAmount: 300,
    unit: "g",
    prepNote: "Thịt bò thái mỏng, bông cải tách miếng vừa ăn",
    techniqueIcon: "chao",
    ingredients: [
      { name: "Thịt bò", amount: 300, unit: "g", prepNote: "Thái lát mỏng ngang thớ" },
      { name: "Bông cải xanh", amount: 300, unit: "g", prepNote: "Tách miếng vừa ăn, chần sơ" },
      { name: "Tỏi", amount: 3, unit: "tép", prepNote: "Băm nhỏ" },
      { name: "Hành tím", amount: 1, unit: "củ", prepNote: "Thái mỏng" },
      { name: "Dầu hào", amount: 1, unit: "muỗng canh", prepNote: "" },
      { name: "Nước tương", amount: 1, unit: "muỗng canh", prepNote: "" },
      { name: "Dầu ăn", amount: 2, unit: "muỗng canh", prepNote: "" },
      { name: "Tiêu", amount: 0.5, unit: "muỗng cà phê", prepNote: "" },
    ],
  },
  {
    slug: "rau-muong-xao-toi",
    title: "Rau Muống Xào Tỏi",
    image: "/images/recipes/rau-muong-xao-toi.png",
    imageAlt: "Rau muống xanh xào tỏi",
    difficulty: "de",
    cookTimeMinutes: 10,
    baseServings: 4,
    category: "Món xào",
    mainIngredient: "Rau muống",
    baseAmount: 500,
    unit: "g",
    prepNote: "Rau muống nhặt sạch, ngâm nước muối rồi để ráo",
    techniqueIcon: "chao",
    ingredients: [
      { name: "Rau muống", amount: 500, unit: "g", prepNote: "Nhặt sạch, cắt khúc" },
      { name: "Tỏi", amount: 4, unit: "tép", prepNote: "Băm nhỏ" },
      { name: "Dầu ăn", amount: 2, unit: "muỗng canh", prepNote: "" },
      { name: "Nước mắm", amount: 1, unit: "muỗng canh", prepNote: "" },
      { name: "Đường", amount: 0.5, unit: "muỗng cà phê", prepNote: "" },
    ],
  },
  {
    slug: "suon-xao-chua-ngot",
    title: "Sườn Xào Chua Ngọt",
    image: "/images/recipes/suon-xao-chua-ngot.png",
    imageAlt: "Sườn xào chua ngọt phủ mè",
    difficulty: "trung-binh",
    cookTimeMinutes: 35,
    baseServings: 4,
    category: "Món xào",
    mainIngredient: "Sườn non",
    baseAmount: 600,
    unit: "g",
    prepNote: "Sườn chặt miếng, chần nhanh rồi rửa sạch",
    techniqueIcon: "chao",
    ingredients: [
      { name: "Sườn non", amount: 600, unit: "g", prepNote: "Chặt miếng, chần nhanh rồi rửa sạch" },
      { name: "Hành tím", amount: 2, unit: "củ", prepNote: "Băm nhỏ" },
      { name: "Tỏi", amount: 3, unit: "tép", prepNote: "Băm nhỏ" },
      { name: "Nước mắm", amount: 2, unit: "muỗng canh", prepNote: "" },
      { name: "Đường", amount: 2, unit: "muỗng canh", prepNote: "" },
      { name: "Giấm", amount: 1, unit: "muỗng canh", prepNote: "" },
      { name: "Tương cà", amount: 2, unit: "muỗng canh", prepNote: "" },
      { name: "Dầu ăn", amount: 2, unit: "muỗng canh", prepNote: "" },
    ],
  },
  {
    slug: "canh-chua-ca-loc",
    title: "Canh Chua Cá Lóc",
    image: "/images/recipes/pho-bo.png",
    imageAlt: "Bát canh nóng với cá và rau thơm",
    difficulty: "trung-binh",
    cookTimeMinutes: 30,
    baseServings: 4,
    category: "Món canh",
    mainIngredient: "Cá lóc",
    baseAmount: 700,
    unit: "g",
    prepNote: "Cá làm sạch, cắt khoanh và để ráo",
    techniqueIcon: "noi",
    ingredients: [
      { name: "Cá lóc", amount: 700, unit: "g", prepNote: "Làm sạch, cắt khoanh" },
      { name: "Dứa", amount: 150, unit: "g", prepNote: "Cắt lát" },
      { name: "Cà chua", amount: 2, unit: "quả", prepNote: "Cắt múi cau" },
      { name: "Bạc hà", amount: 150, unit: "g", prepNote: "Tước vỏ, cắt lát xéo" },
      { name: "Đậu bắp", amount: 100, unit: "g", prepNote: "Cắt xéo" },
      { name: "Giá đỗ", amount: 100, unit: "g", prepNote: "Rửa sạch" },
      { name: "Me chua", amount: 40, unit: "g", prepNote: "Dầm lấy nước cốt" },
      { name: "Rau om", amount: 1, unit: "nhánh", prepNote: "Cắt nhỏ" },
      { name: "Ngò gai", amount: 2, unit: "lá", prepNote: "Cắt nhỏ" },
      { name: "Nước mắm", amount: 2, unit: "muỗng canh", prepNote: "" },
      { name: "Đường", amount: 1, unit: "muỗng canh", prepNote: "" },
    ],
  },
  {
    slug: "chao-ga-xe-phay",
    title: "Cháo Gà Xé Phay",
    image: "/images/recipes/chao-ga.png",
    imageAlt: "Bát cháo gà xé phay",
    difficulty: "de",
    cookTimeMinutes: 25,
    baseServings: 3,
    category: "Món canh",
    mainIngredient: "Thịt gà",
    baseAmount: 400,
    unit: "g",
    prepNote: "Gà rửa sạch, luộc chín rồi xé sợi",
    techniqueIcon: "noi",
    ingredients: [
      { name: "Thịt gà", amount: 400, unit: "g", prepNote: "Rửa sạch, luộc chín rồi xé sợi" },
      { name: "Gạo tẻ", amount: 150, unit: "g", prepNote: "Vo sạch, rang sơ nếu thích" },
      { name: "Hành tím", amount: 2, unit: "củ", prepNote: "Băm nhỏ" },
      { name: "Gừng", amount: 20, unit: "g", prepNote: "Thái lát" },
      { name: "Hành lá", amount: 2, unit: "nhánh", prepNote: "Cắt nhỏ" },
      { name: "Rau răm", amount: 1, unit: "nhánh", prepNote: "Cắt nhỏ" },
      { name: "Nước mắm", amount: 1, unit: "muỗng canh", prepNote: "" },
      { name: "Muối", amount: 1, unit: "muỗng cà phê", prepNote: "" },
    ],
  },
  {
    slug: "cha-gio-hai-san",
    title: "Chả Giò Hải Sản",
    image: "/images/recipes/goi-cuon-tom-thit.png",
    imageAlt: "Món cuốn hải sản ăn kèm rau xanh",
    difficulty: "trung-binh",
    cookTimeMinutes: 45,
    baseServings: 3,
    category: "Món chiên",
    mainIngredient: "Hải sản",
    baseAmount: 350,
    unit: "g",
    prepNote: "Tôm mực làm sạch, thái hạt lựu và để ráo",
    techniqueIcon: "chao",
    ingredients: [
      { name: "Tôm", amount: 200, unit: "g", prepNote: "Bóc vỏ, băm thô" },
      { name: "Mực", amount: 150, unit: "g", prepNote: "Làm sạch, thái hạt lựu" },
      { name: "Khoai môn", amount: 100, unit: "g", prepNote: "Bào sợi" },
      { name: "Cà rốt", amount: 1, unit: "củ", prepNote: "Bào sợi" },
      { name: "Bánh tráng bò bía", amount: 20, unit: "cái", prepNote: "" },
      { name: "Hành tím", amount: 2, unit: "củ", prepNote: "Băm nhỏ" },
      { name: "Tỏi", amount: 2, unit: "tép", prepNote: "Băm nhỏ" },
      { name: "Trứng gà", amount: 1, unit: "quả", prepNote: "Đánh tan để quét mép cuốn" },
      { name: "Dầu ăn", amount: 400, unit: "ml", prepNote: "Để chiên ngập dầu" },
    ],
  },
  {
    slug: "banh-xeo-mien-tay",
    title: "Bánh Xèo Miền Tây",
    image: "/images/recipes/banh-xeo-mien-tay.png",
    imageAlt: "Bánh xèo vàng giòn với rau thơm",
    difficulty: "trung-binh",
    cookTimeMinutes: 35,
    baseServings: 3,
    category: "Món chiên",
    mainIngredient: "Bột bánh xèo",
    baseAmount: 300,
    unit: "g",
    prepNote: "Pha bột với nước theo tỷ lệ, để nghỉ 15 phút",
    techniqueIcon: "chao",
    ingredients: [
      { name: "Bột bánh xèo", amount: 300, unit: "g", prepNote: "Pha theo hướng dẫn gói bột" },
      { name: "Nước cốt dừa", amount: 200, unit: "ml", prepNote: "" },
      { name: "Bia", amount: 100, unit: "ml", prepNote: "Giúp vỏ bánh giòn hơn" },
      { name: "Tôm", amount: 200, unit: "g", prepNote: "Rửa sạch" },
      { name: "Thịt ba chỉ", amount: 200, unit: "g", prepNote: "Thái mỏng" },
      { name: "Giá đỗ", amount: 200, unit: "g", prepNote: "Rửa sạch" },
      { name: "Hành lá", amount: 3, unit: "nhánh", prepNote: "Cắt nhỏ" },
      { name: "Rau sống", amount: 1, unit: "rổ", prepNote: "Rửa sạch, để ráo" },
      { name: "Dầu ăn", amount: 4, unit: "muỗng canh", prepNote: "" },
    ],
  },
  {
    slug: "ca-hap-gung",
    title: "Cá Hấp Gừng",
    image: "/images/recipes/bo-bop-thau.png",
    imageAlt: "Món cá hấp với rau củ và gừng",
    difficulty: "de",
    cookTimeMinutes: 40,
    baseServings: 4,
    category: "Món hấp",
    mainIngredient: "Cá nguyên con",
    baseAmount: 1,
    unit: "con",
    prepNote: "Cá làm sạch, khứa nhẹ hai mặt và thấm khô",
    techniqueIcon: "hap",
    ingredients: [
      { name: "Cá diêu hồng", amount: 1, unit: "con", prepNote: "Làm sạch, khứa nhẹ hai mặt" },
      { name: "Gừng", amount: 50, unit: "g", prepNote: "Thái sợi" },
      { name: "Hành lá", amount: 4, unit: "nhánh", prepNote: "Cắt khúc" },
      { name: "Hành tây", amount: 1, unit: "củ", prepNote: "Cắt múi cau" },
      { name: "Nước tương", amount: 2, unit: "muỗng canh", prepNote: "" },
      { name: "Dầu hào", amount: 1, unit: "muỗng canh", prepNote: "" },
      { name: "Dầu ăn", amount: 1, unit: "muỗng canh", prepNote: "Để phi hành" },
    ],
  },
  {
    slug: "nam-xao-dau-hu-chay",
    title: "Nấm Xào Đậu Hũ Chay",
    image: "/images/recipes/nam-xao-dau-hu.png",
    imageAlt: "Nấm xào đậu hũ với ớt chuông",
    difficulty: "de",
    cookTimeMinutes: 15,
    baseServings: 2,
    category: "Món chay",
    mainIngredient: "Nấm và đậu hũ",
    baseAmount: 350,
    unit: "g",
    prepNote: "Nấm lau sạch, đậu hũ cắt miếng vuông",
    techniqueIcon: "chao",
    ingredients: [
      { name: "Nấm rơm", amount: 200, unit: "g", prepNote: "Lau sạch, cắt đôi" },
      { name: "Đậu hũ", amount: 2, unit: "miếng", prepNote: "Cắt miếng vuông" },
      { name: "Ớt chuông", amount: 1, unit: "quả", prepNote: "Cắt miếng vừa ăn" },
      { name: "Tỏi", amount: 2, unit: "tép", prepNote: "Băm nhỏ" },
      { name: "Hành boa rô", amount: 1, unit: "nhánh", prepNote: "Thái lát" },
      { name: "Nước tương", amount: 1, unit: "muỗng canh", prepNote: "" },
      { name: "Dầu hào chay", amount: 1, unit: "muỗng canh", prepNote: "" },
      { name: "Dầu ăn", amount: 2, unit: "muỗng canh", prepNote: "" },
    ],
  },
  {
    slug: "pho-bo-gia-truyen",
    title: "Phở Bò Gia Truyền",
    image: "/images/recipes/pho-bo.png",
    imageAlt: "Bát phở bò nóng với rau thơm",
    difficulty: "kho",
    cookTimeMinutes: 120,
    baseServings: 6,
    category: "Món canh",
    mainIngredient: "Xương ống và thịt bò",
    baseAmount: 1500,
    unit: "g",
    prepNote: "Xương chần sạch, thịt bò thái lát mỏng ngang thớ",
    techniqueIcon: "noi",
    ingredients: [
      { name: "Xương ống bò", amount: 1000, unit: "g", prepNote: "Chần sạch trước khi hầm" },
      { name: "Thịt bò", amount: 500, unit: "g", prepNote: "Thái lát mỏng ngang thớ" },
      { name: "Bánh phở", amount: 600, unit: "g", prepNote: "Trụng nóng trước khi ăn" },
      { name: "Hành tây", amount: 1, unit: "củ", prepNote: "Nướng sơ" },
      { name: "Gừng", amount: 50, unit: "g", prepNote: "Nướng sơ, đập dập" },
      { name: "Hoa hồi", amount: 3, unit: "cái", prepNote: "Rang thơm" },
      { name: "Quế", amount: 1, unit: "thanh", prepNote: "Rang thơm" },
      { name: "Thảo quả", amount: 1, unit: "quả", prepNote: "Rang thơm" },
      { name: "Đinh hương", amount: 5, unit: "nụ", prepNote: "Rang thơm" },
      { name: "Nước mắm", amount: 3, unit: "muỗng canh", prepNote: "" },
      { name: "Đường phèn", amount: 20, unit: "g", prepNote: "" },
      { name: "Hành lá", amount: 3, unit: "nhánh", prepNote: "Cắt nhỏ" },
      { name: "Rau thơm", amount: 1, unit: "rổ", prepNote: "Rửa sạch, để ráo" },
    ],
  },
];
